production: &production
  url: <%= ENV.fetch("DATA_REDIS_URL", "redis://127.0.0.1:6378/0") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("DATA_REDIS_URL", "redis://127.0.0.1:6378/0") %>
  timeout: 1

staging: &staging
  url: <%= ENV.fetch("DATA_REDIS_URL", "redis://127.0.0.1:6377/1") %>
  timeout: 1

test:
  <<: *development
